# Generated by Django 5.2.1 on 2025-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionLog',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('CANCEL', 'Cancelar')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accion_log',
            },
        ),
    ]
