# Generated by Django 5.2.1 on 2025-06-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionLog',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('CANCEL', 'Cancelar')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codigo_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva')),
                ('dni_administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.administrador')),
            ],
            options={
                'db_table': 'accion_log',
                'indexes': [models.Index(fields=['codigo_reserva'], name='idx_log_reserva'), models.Index(fields=['dni_administrador'], name='idx_log_admin'), models.Index(fields=['created_at'], name='idx_log_fecha'), models.Index(fields=['accion'], name='idx_log_accion')],
            },
        ),
    ]
