# Generated by Django 5.2.1 on 2025-06-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('personal', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionlog',
            name='codigo_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='accionlog',
            name='dni_administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.administrador'),
        ),
        migrations.AddIndex(
            model_name='accionlog',
            index=models.Index(fields=['codigo_reserva'], name='idx_log_reserva'),
        ),
        migrations.AddIndex(
            model_name='accionlog',
            index=models.Index(fields=['dni_administrador'], name='idx_log_admin'),
        ),
        migrations.AddIndex(
            model_name='accionlog',
            index=models.Index(fields=['created_at'], name='idx_log_fecha'),
        ),
        migrations.AddIndex(
            model_name='accionlog',
            index=models.Index(fields=['accion'], name='idx_log_accion'),
        ),
    ]
