# Generated by Django 5.2.1 on 2025-06-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista'), ('SUPERVISOR', 'Supervisor')], default='RECEPCIONISTA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_tipo_doc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='huespedes.tipodocumento')),
            ],
            options={
                'db_table': 'administrador',
                'indexes': [models.Index(fields=['username'], name='idx_admin_username'), models.Index(fields=['email'], name='idx_admin_email'), models.Index(fields=['rol'], name='idx_admin_rol')],
            },
        ),
    ]
