# Generated by Django 5.2.1 on 2025-06-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('permite_reserva', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estado_habitacion',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.IntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_habitacion',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10, unique=True)),
                ('piso', models.IntegerField()),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ultima_limpieza', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='habitaciones.estadohabitacion')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habitaciones.tipohabitacion')),
            ],
            options={
                'db_table': 'habitacion',
                'indexes': [models.Index(fields=['id_tipo'], name='idx_habitacion_tipo'), models.Index(fields=['id_estado'], name='idx_habitacion_estado'), models.Index(fields=['piso'], name='idx_habitacion_piso')],
            },
        ),
    ]
