# Generated by Django 5.2.1 on 2025-05-29 12:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contrasenia', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'db_table': 'duenio',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('MATRIMONIAL', 'Matrimonial'), ('SUITE', 'Suite')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'Mantenimiento'), ('LIMPIEZA', 'Limpieza')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por noche')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitacion',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contrasenia', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('visitas', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Descuento (%)')),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'db_table': 'huesped',
            },
        ),
        migrations.CreateModel(
            name='AccionRetiro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('fecha_retiro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Retiro')),
                ('duenio', models.ForeignKey(db_column='fk_nom_due', on_delete=django.db.models.deletion.CASCADE, to='servicios.duenio', verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Acción de Retiro',
                'verbose_name_plural': 'Acciones de Retiro',
                'db_table': 'accion_retiro',
            },
        ),
        migrations.CreateModel(
            name='LibroCuenta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('accion', models.CharField(choices=[('INGRESO', 'Ingreso'), ('RETIRO', 'Retiro')], max_length=20, verbose_name='Acción')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Actual')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('accion_retiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.accionretiro', verbose_name='Acción de Retiro')),
            ],
            options={
                'verbose_name': 'Libro de Cuenta',
                'verbose_name_plural': 'Libro de Cuentas',
                'db_table': 'libro_cuenta',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='LibroEstancia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('medio_pago', models.CharField(max_length=50, verbose_name='Medio de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('administrador', models.ForeignKey(db_column='fk_dni_admin', on_delete=django.db.models.deletion.CASCADE, to='servicios.administrador', verbose_name='Administrador')),
                ('habitacion', models.ForeignKey(db_column='fk_hab_cod', on_delete=django.db.models.deletion.CASCADE, to='servicios.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(db_column='fk_dni_hue', on_delete=django.db.models.deletion.CASCADE, to='servicios.huesped', verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Libro de Estancia',
                'verbose_name_plural': 'Libro de Estancias',
                'db_table': 'libro_estancia',
                'ordering': ['-fecha_entrada', '-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='AccionIngreso',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('habitacion', models.ForeignKey(db_column='fk_hab_cod', on_delete=django.db.models.deletion.CASCADE, to='servicios.habitacion', verbose_name='Habitación')),
                ('libro_estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.libroestancia', verbose_name='Libro de Estancia')),
            ],
            options={
                'verbose_name': 'Acción de Ingreso',
                'verbose_name_plural': 'Acciones de Ingreso',
                'db_table': 'accion_ingreso',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('hora_ingreso', models.TimeField(verbose_name='Hora de Ingreso')),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado de Reserva')),
                ('habitacion', models.ForeignKey(db_column='fk_hab_cod', on_delete=django.db.models.deletion.CASCADE, to='servicios.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(db_column='fk_dni_hue', on_delete=django.db.models.deletion.CASCADE, to='servicios.huesped', verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
