# Generated by Django 5.2.1 on 2025-07-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_change_password_usuario_id_tipo_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='total_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
