# Generated by Django 5.2.1 on 2025-06-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('huespedes', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobrar',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva')),
                ('dni_huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='huespedes.huesped')),
            ],
            options={
                'db_table': 'cuenta_cobrar',
                'indexes': [models.Index(fields=['codigo_reserva'], name='idx_cuenta_reserva'), models.Index(fields=['dni_huesped'], name='idx_cuenta_huesped'), models.Index(fields=['estado'], name='idx_cuenta_estado'), models.Index(fields=['fecha_vencimiento'], name='idx_cuenta_vencimiento')],
            },
        ),
    ]
