# Generated by Django 5.2.1 on 2025-06-26 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacobrar',
            name='codigo_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='cuentacobrar',
            name='dni_huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cuentacobrar',
            index=models.Index(fields=['codigo_reserva'], name='idx_cuenta_reserva'),
        ),
        migrations.AddIndex(
            model_name='cuentacobrar',
            index=models.Index(fields=['dni_huesped'], name='idx_cuenta_huesped'),
        ),
        migrations.AddIndex(
            model_name='cuentacobrar',
            index=models.Index(fields=['estado'], name='idx_cuenta_estado'),
        ),
        migrations.AddIndex(
            model_name='cuentacobrar',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_cuenta_vencimiento'),
        ),
    ]
