# Generated by Django 5.2.1 on 2025-07-08 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_reserva',
        ),
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_huesped',
        ),
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_estado',
        ),
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_vencimiento',
        ),
        migrations.AddField(
            model_name='cuentacobrar',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='dni_huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='id_cuenta',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
