# Generated by Django 5.2.1 on 2025-07-06 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_reserva',
        ),
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_huesped',
        ),
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_estado',
        ),
        migrations.RemoveIndex(
            model_name='cuentacobrar',
            name='idx_cuenta_vencimiento',
        ),
        migrations.AddField(
            model_name='cuentacobrar',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='id_cuenta',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
