# Generated by Django 5.2.1 on 2025-06-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('longitud_minima', models.IntegerField(default=8)),
                ('longitud_maxima', models.IntegerField(default=12)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(default='Peruana', max_length=50)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('visitas_totales', models.IntegerField(default=0)),
                ('change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huespedes', to='huespedes.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'db_table': 'huesped',
                'indexes': [models.Index(fields=['nombres'], name='idx_huesped_nombres'), models.Index(fields=['apellidos'], name='idx_huesped_apellidos'), models.Index(fields=['email'], name='idx_huesped_email')],
            },
        ),
    ]
