# Generated by Django 5.2.1 on 2025-06-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='change_password',
        ),
    ]
