# Generated by Django 5.2.1 on 2025-06-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0002_remove_huesped_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
    ]
