# Generated by Django 5.2.1 on 2025-06-22 21:17

import huespedes.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0002_alter_huesped_managers_huesped_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='huesped',
            managers=[
                ('objects', huespedes.models.HuespedManager()),
            ],
        ),
    ]
