# Generated by Django 5.2.1 on 2025-06-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0003_alter_huesped_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='user_permissions',
        ),
    ]
