# Generated by Django 5.2.1 on 2025-07-03 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_estado_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('es_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Reserva',
                'verbose_name_plural': 'Historiales de Reserva',
                'db_table': 'historial_reserva',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_checkin_programado', models.DateTimeField()),
                ('fecha_checkout_programado', models.DateTimeField()),
                ('fecha_checkin_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_checkout_real', models.DateTimeField(blank=True, null=True)),
                ('numero_huespedes', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id_tipo_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_presencia', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_reserva',
            },
        ),
    ]
