# Generated by Django 5.2.1 on 2025-06-26 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '__first__'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_estado_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('es_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id_tipo_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_presencia', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_reserva',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_checkin_programado', models.DateTimeField()),
                ('fecha_checkout_programado', models.DateTimeField()),
                ('fecha_checkin_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_checkout_real', models.DateTimeField(blank=True, null=True)),
                ('numero_huespedes', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habitaciones.habitacion')),
                ('dni_administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.administrador')),
                ('dni_huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_estado_reserva', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reservas.estadoreserva')),
                ('id_tipo_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.tiporeserva')),
            ],
            options={
                'db_table': 'reserva',
                'indexes': [models.Index(fields=['codigo_habitacion'], name='idx_reserva_habitacion'), models.Index(fields=['dni_huesped'], name='idx_reserva_huesped'), models.Index(fields=['dni_administrador'], name='idx_reserva_admin'), models.Index(fields=['fecha_checkin_programado', 'fecha_checkout_programado'], name='idx_reserva_fechas'), models.Index(fields=['id_estado_reserva'], name='idx_reserva_estado'), models.Index(fields=['id_tipo_reserva'], name='idx_reserva_tipo')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_checkout_programado__gt', models.F('fecha_checkin_programado'))), name='chk_fechas_validas'), models.CheckConstraint(condition=models.Q(('precio_noche__gt', 0)), name='chk_precio_positivo')],
            },
        ),
    ]
