# Generated by Django 5.2.1 on 2025-06-28 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_administradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_tipo_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.tiporeserva'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['codigo_habitacion'], name='idx_reserva_habitacion'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario'], name='idx_reserva_huesped'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario_admin'], name='idx_reserva_admin'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_checkin_programado', 'fecha_checkout_programado'], name='idx_reserva_fechas'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['id_estado_reserva'], name='idx_reserva_estado'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['id_tipo_reserva'], name='idx_reserva_tipo'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_checkout_programado__gt', models.F('fecha_checkin_programado'))), name='chk_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('precio_noche__gt', 0)), name='chk_precio_positivo'),
        ),
    ]
