# Generated by Django 5.2.1 on 2025-07-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_historialreserva_huesped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='descuento',
        ),
    ]
